# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GETit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GETit

pod 'GoogleSignIn'

  target 'GETit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  end

  target 'GETitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


